Hotfix/#12/fix domain
UMC-TEAM-RF/RF-Server pull request #14
Opened 2023-07-18 12:34 UTC by kuk6933

main에.. merge해도 될까요?

2023-07-18 13:55 UTC, minjgziii approved these changes
수고하셨습니당 굿맨!!

2023-07-18 16:59 UTC, jaewonLeeKOR requested changes
GeneratedValue 어노테이션의 옵션이 기본값으로 GenerationType.AUTO로 들어가는데 이렇게 하면 테이블이 제대로 생성되지 않고 '_seq' 이 붙은 테이블이 함께 생성되는것을 확인했습니다.
혹시 의도한건건걸까요? 🤔
이 부분을 GenerationType.IDENTITY로 바꿔야 해당 테이블이 생성되지 않았습니다. 🤗

2023-07-19 05:12 UTC, jaewonLeeKOR approved these changes
Good 👍🏻

2023-07-19 05:13 UTC, lxxyxin commented
굿맨짱~👍

2023-07-19 05:14 UTC, jaewonLeeKOR commented
> 굿맨짱~👍

Approve를 날려주세용,,,, 굿맨짱걸님 ㅎㅎ

2023-07-19 05:44 UTC, lxxyxin approved these changes

2023-07-19 05:45 UTC, merged