Feature/#10/party crud
UMC-TEAM-RF/RF-Server pull request #20
Opened 2023-07-22 06:03 UTC by kuk6933

Interest가 16개로 고정되어 있기에 테이블보다 enum응 사용하는게 더 효율적이라고 생각해서 바꿔봤습니다

기존 PartyPartyInterest -> PartyInterest 변경
기존 PartyInterest -> constant/Interest
Constant에 Interest추가 (domain의 Interest랑은 다름 혹시 몰라서 Interest Entity는 아직 삭제 안했습니다) 

Party의 interest 변수 @OneToMany 뒤에 mappedBy를 붙인 이유는 PartyInterest에 FK가 있기 때문에 연관관계의 주인으로 정했습니다. 

혹 이상한거나 바꿔야할 부분, 궁금한부분 있으면 리뷰 달아주세요!

2023-07-22 06:04 UTC, kuk6933 commented
tags나 rule같은 경우는 핵심기능 구현하고 추후에 구현하는게 맞다고 생각되어서 주석처리 해뒀습니다

2023-07-22 06:06 UTC, jaewonLeeKOR commented
로컬에서 직접 돌려보고 의도대로 실행이 잘 됐나요?

2023-07-22 06:07 UTC, kuk6933 commented
넵 다 실행됐습니다

2023-07-22 07:59 UTC, jaewonLeeKOR requested changes

2023-07-22 07:59 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +    }
생성자와 클래스의 party, party interest 의 선언부의 위치를 바꾸는게 더 직관적일거 같아요

2023-07-22 07:59 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +    }
여기서 toString이 어떤 역할을 하나요?

2023-07-22 07:59 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/constant/Interest.java
> +    FOOD(8), COOKING(9), HOT_PLACE(10), CAFE(11), STUDY(12), MAJOR(13), GRADE(14), READING(15);
enum은 이미 상수 정보를 가지고 있는데 id값으로 재정의 한 이유가 뭔가요?

2023-07-22 11:29 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/Party.java
> +    @JoinTable(name = "User" // ?
잠깐 표시용으로 쓴거였는디 안지웠었네용

2023-07-22 11:30 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +    }
테스트할때 로그로 찍으려고 만든 코드입니다

2023-07-22 11:31 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/constant/Interest.java
> +    FOOD(8), COOKING(9), HOT_PLACE(10), CAFE(11), STUDY(12), MAJOR(13), GRADE(14), READING(15);
상수 타입으로 바로 못받는줄 알고 정수값으로 받을까 해서 넣었었던 코드입니다 수정할게용~

2023-07-22 11:32 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +    }
넹~

2023-07-22 11:36 UTC, lxxyxin requested changes

2023-07-22 11:36 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +
JsonIgnore 어노테이션이 여기서 하는 역할이 어떤건가요 ?-? 잘 몰라서 질문함니당

2023-07-22 11:36 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/party/PartyService.java
> +    public GetPartyRes getGroup(Long groupId) throws BaseException {
다른거 다 party로 되어있는데 얘만 group으로 되어있어서 함수명 수정 필요할거같아용

2023-07-22 11:41 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +    }
아 정확히 얘기를 안했었네요
파라미터 위치 말고 (생성자)와 (party, party interest의 선언부)의 위치를 바꾸는걸 말하는거였어요 🤗

2023-07-22 11:44 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/PartyService.java
> +    public DeletePartyRes deleteParty(Long groupId) throws BaseException {
여기도 groupId라 partyId로 바꿔야할거 같아요

2023-07-22 12:15 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +    }
앗  넵

2023-07-22 12:15 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/PartyService.java
> +    public GetPartyRes getGroup(Long groupId) throws BaseException {
넵!!

2023-07-22 12:17 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +
PartyInterest가 Party를 참조하고 Party도 PartyInterest도 참조합니다. 이러한 관계에서는 순환참조가 일어나는데 해당 어노테이션으로 해결할 수 있습니다!

2023-07-22 12:30 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/domain/PartyInterest.java
> +
역시 멋쟁이는 다르다.... 감사합니당

2023-07-22 12:35 UTC, kuk6933 commented
남은 group들 다 박멸해버렸슴니다

2023-07-22 13:12 UTC, jaewonLeeKOR approved these changes
고생했어요!! 🙋🏻‍♂️

2023-07-22 14:20 UTC, lxxyxin approved these changes

2023-07-22 14:21 UTC, lxxyxin commented
고생했서용~~

2023-07-22 15:05 UTC, minjgziii approved these changes
group killer, 고생하셨습니다!

2023-07-22 15:47 UTC, merged

2023-07-23 10:24 UTC, jaewonLeeKOR commented
이슈 살려서 다시 테스트 해보고 머지 해주세요~ 돌려봤는데 오류가 좀 나네요