Feature/#9/utils
UMC-TEAM-RF/RF-Server pull request #32
Opened 2023-07-27 10:04 UTC by minjgziii

2023-07-28 03:14 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        universityNameMap.put("tukorea.ac.kr", "한국공항대학교");
오타있어요! 🫣

2023-07-28 03:40 UTC, minjgziii commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        universityNameMap.put("tukorea.ac.kr", "한국공항대학교");
넵 수정했습니당!

2023-07-28 05:55 UTC, jaewonLeeKOR requested changes

2023-07-28 05:55 UTC, jaewonLeeKOR commented on build.gradle
> +	implementation 'io.lettuce:lettuce-core:6.2.1.RELEASE' // redis 통신 프레임워크
redis 사용하지 않는다고 했던거 같은데 사용하는건가요? 🧐

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
> +    MAIL_SEND_SUCCESS(true, 6000, "이메일이 성공적으로 전송되었습니다."),
이메일 전송이 성공했을때 1000번 코드를 사용하지 않고 새로운 오류 상태 코드로 전송하는 이유가 뭔가요??

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/PartyPartyInterest.java
이 파일은 메인 브랜치에서 제거된 파일이라 삭제하고 다시 커밋해야할거 같아요!!

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/dto/PostSendReq.java
> +    private String code;
postSendReq는 인증코드가 생성되기 전에 인증코드를 요청하기위한 DTO로 알고 있는데 code가 필요없지 않을까요??

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +            throw new BaseException(INVALID_MAIL);
INVALID_MAIL이 메일 형식에 대한 예외처리인거 같은데
INVALID_MAIL가 담당하는 예외처리 범위가 너무 넓은거 같아요
지금은 아니어도 다른 개발이 끝난 이후에 범위를 좁혔으면 좋겠어요

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        org.rf.rfserver.domain.MailMessage mailTitle = org.rf.rfserver.domain.MailMessage.MAIL_TITLE;
MailMessage를 import해서 사용하는게 가독성이 더 나을거 같아요

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        String koreanUniversity = universityNameMap.getOrDefault(university, university);
unviersityNameMap에 들어있지 않은 대학교는 제외하려면 getOrDefault의 두번째 파라미터로 다른값이 들어가야 구분이 가지 않나요?
동일한 값을 넣은 이유가 따로 있을까요??

2023-07-28 05:55 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        String koreanUniversity = universityNameMap.getOrDefault(university, university);
위와 같은 질문입니다.

2023-07-28 06:12 UTC, lxxyxin requested changes

2023-07-28 06:12 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +    @Autowired
final로 선언된 필드의 경우 @Autowired 어노테이션이 작동하지 않아서 이 어노테이션은 빼도 될 거 같습니당
저번에 동동이 @Autowired 사용은 지양하는게 낫다고 말해줬어요

2023-07-28 13:24 UTC, minjgziii commented on src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
> +    MAIL_SEND_SUCCESS(true, 6000, "이메일이 성공적으로 전송되었습니다."),
현재 이메일 전송/인증 성공했을 때 1000번 코드를 사용하여 오류 상태 코드를 보내고 있습니다. 쓸데없이 만들어 놓고 쓰지도 않았네여 삭제하겠습니다!

2023-07-28 13:51 UTC, minjgziii commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        String koreanUniversity = universityNameMap.getOrDefault(university, university);
대학교 이름이 universityNameMap 에 존재하지 않는 경우, koreanUniversity에는 이메일에서 추출한 영어로 된 대학교 이름인 university가 그대로 저장되기 때문에 Map 존재하지 않는 대학교에 대해서는 오류 코드를 전송합니다.

2023-07-28 17:22 UTC, jaewonLeeKOR requested changes

2023-07-28 17:22 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/mail/service/MailService.java
> +        String koreanUniversity = universityNameMap.getOrDefault(university, university);
Map의 .get()을 사용해도 되지않을까 조심스럽게 생각해봅니다 이부분은 어떤가요?

2023-07-29 05:02 UTC, jaewonLeeKOR approved these changes

2023-07-29 05:05 UTC, kuk6933 approved these changes
고생하셨습니다!

2023-07-29 05:30 UTC, merged