Feature/#35/block
UMC-TEAM-RF/RF-Server pull request #39
Opened 2023-08-01 08:36 UTC by minjgziii

2023-08-01 13:58 UTC, kuk6933 requested changes

2023-08-01 13:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        User user = optionalUser.get();
Optional으로 받고 if로 검증하기보다는 
User user = userRepository.findById(userId)
                         .orElseThrow(() -> new BaseException(USER_NOT_FOUND)); 로 고치는게 좋을거같아요!

2023-08-01 13:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        return party;
userParty에 user와 party를 넣어줬다면 양방향이므로 user와 party에도 UserParty를 넣어줘야합니다!

2023-08-01 13:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        return party;
연관관계 편의메서드를 사용하면 조금 더 수월하게 할 수 있습니다! :)

2023-08-01 13:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
여기도 위와 같이 orElseThrow로 하면 좋을것 같습니다!

2023-08-01 13:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +
위에서 리뷰한 것과 같이 연관관계 편의 메서드를 적용하면 여기도 같이 되겠네용

2023-08-01 13:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +
여기도 User가 가지고 있는 UserParty, 
Party가 가지고 있는 UserParty를 지워줘야 할 듯 합니다!

2023-08-01 16:21 UTC, minjgziii commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
다른 부분은 orElseThrow로 바꿨는데용!

이 부분은 
UserParty userParty = userPartyRepository.findByUserAndParty(user, party)
                .orElse(null);
        if (userParty != null) {
            throw new BaseException(ALREADY_JOINED_PARTY);
        }

이렇게 바꿔서 실행해 봤더니 Entity must not be null 에러가 뜨네요.

이 부분은 Optional을 사용하는 게 나을 것 같은데, 어떻게 생각하시나용?!
에러 안 뜨게 orElseThrow를 사용하는 방법을 아신다면 알려주세용😢

2023-08-01 16:40 UTC, minjgziii commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
이렇게 하면 예외가 발생하는 시점이 "이미 모임에 참여한 사용자"를 찾을 때가 아니라 "모임에 참여하지 않은 사용자"를 찾을 때 발생하게 됩니다!
즉, 가입이 되어있으면 예외가 발생되어야 하는데 가입이 안 되어 있을 때, 이미 가입됐다는 예외가 발생합니당

저도 처음에 이렇게 썼다가 저 코드로 바꿨어요!!

2023-08-01 16:43 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
아아 잘 바꾸셨다는 코멘트를 못보고 코멘트를 썼네용 ㅎ 굿!

2023-08-03 10:50 UTC, jaewonLeeKOR approved these changes
진짜 많이 짰네요오... 진짜진짜 고생많아써요!! 🤪

2023-08-03 13:41 UTC, jaewonLeeKOR requested changes

2023-08-03 13:41 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    }
차단 관련 메소드를 party를 관리하는 partyController보다는 blockController에 있는게 나을 거 같아요
지금은
/party/block/{userId}/{partyId}
식으로 접근하는데
/block/party/{userId}/{partyId} 
식으로 바꾸면 프론트에서 사용하기에도 URL이 더 직관적일거 같아요

2023-08-03 13:41 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    }
차단 여부를 조회를 해보지 않고 프론트에서 알 방법이 없으니 non-blocked 를 붙이기 보다 /user/{userId} 와 같은 형식으로 바꾸는게 나을거 같아요

2023-08-03 15:37 UTC, lxxyxin requested changes

2023-08-03 15:37 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    @PostMapping(value = "/join")
얘만 value = "/join" 으로 적혀있는데 그냥 value 빼고 "/join"으로 수정해도 되지 않을까요?

2023-08-05 07:58 UTC, jaewonLeeKOR requested changes

2023-08-05 07:58 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/blockUser/service/BlockUserService.java
> +            System.out.println(blockRes);
merge 하기 전 마지막으로 커밋할때 로그 찍어보는용의 코드는 지워주세요~!!

2023-08-05 07:58 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/blockUser/dto/GetBlockUserRes.java
> +    private User blocked;
그동안 다들 에러 발생하는거 보면
엔티티 자체를 반환하는 Response는 좋지 않은거 같아요~
User 엔티티보다 해당 엔티티에서 클라이언트가 필요한 컬럼만 불러와 반환하는 형태로 바꾸는게 어떨까요?
제안하는거예요~~

2023-08-05 07:58 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/blockUser/dto/PostBlockUserReq.java
> +    private User blocked;
제가 잘 몰라서 그러는데 객체형태로 Request를 받을 수 있었나요?

2023-08-05 07:58 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/BlockParty.java
> +    @JsonBackReference
JsonIgnore 어노테이션은 json serialize할 때 null 값으로 할당하는 어노테이션으로 알고 있는데
JsonBackReference 어노테이션과 함께사용한 이유가 있을까요?

2023-08-05 12:53 UTC, minjgziii commented on src/main/java/org/rf/rfserver/party/repository/BlockPartyRepository.java
지금 blockUser 패키지가 있어서 구분하기 위해 blockParty 패키지를 따로 만들어서 이동시킬게용

2023-08-05 13:01 UTC, minjgziii commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    }
지금 PartyController 코드 상단에 @RequestMapping("/party")로 해 놔서 그렇게 바꾸면 /party/block/party/{userId}/{partyId} 로 되는데 기존 방법으로 하는 게 낫지 않을까요?

2023-08-05 13:17 UTC, minjgziii commented on src/main/java/org/rf/rfserver/domain/BlockParty.java
> +    @JsonBackReference
이 부분은 사용자 차단 관련 코드입니다!

2023-08-05 13:35 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    }
아 BlockController로 메소드 자체를 옮기는게 어떤가 하는 얘기였어요!!

2023-08-09 09:23 UTC, minjgziii commented
페이징 처리 추가하였습니다.

2023-08-09 12:08 UTC, jaewonLeeKOR requested changes
고생하셨네요~ 😳

2023-08-09 12:08 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    public BaseResponse<List<GetPartyRes>> getUsersParties(@PathVariable("userId") Long userId) {
이 부분도 페이징 처리를 했으면 좋겠어요!!
또한 현재 Page 위치를 알기 위한 Base 클래스를 생성해 반환해주면 좋을거 같아요

2023-08-09 12:08 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    public BaseResponse<List<GetPartyRes>> getNonBlockedParties(@PathVariable("userId") Long userId, Pageable pageable) {
현재 Page 위치를 알기 위한 Base 클래스를 생성해 반환해주면 좋을거 같아요

2023-08-09 12:08 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    public DeletePartyRes deleteParty(Long partyId) throws BaseException {
Transaction 어노테이션 사용해야 하지 않나요?
혹시 쓰지 않은 다른 이유가 있을까요? 🫡

2023-08-09 12:29 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/party/controller/PartyController.java
> +    public BaseResponse<Party> createParty(@RequestParam("userId") Long userId, @RequestPart("postPartyReq") PostPartyReq postPartyReq, @RequestPart("file") MultipartFile file) {
그건 제가 해결해보겟읍니다...

2023-08-10 08:05 UTC, minjgziii commented
리뷰 반영했습니다. 
다시 확인해 주세요~~~~~~~~~~

2023-08-10 10:15 UTC, jaewonLeeKOR approved these changes
따봉 민지야!! 정말 잘 하는구나!! 내가 다 뿌듯하다 야

2023-08-10 10:15 UTC, jaewonLeeKOR commented on src/main/resources/application.yml
> +      ddl-auto: update
update로 변경하시고 싶은거죠?
반영할때가 된거 같긴 했어요!! 역시 퀸민지 생각이 깊네요!

2023-08-10 12:07 UTC, lxxyxin approved these changes
따봉민지야 고생했어~

2023-08-10 13:10 UTC, merged