Feature/#1/entity
UMC-TEAM-RF/RF-Server pull request #4
Opened 2023-07-14 06:24 UTC by kuk6933

ERD 기준으로 만들어보았습니다. 
네이밍, 연관관계매핑 수정해야할 곳 있으면 말씀주세용 
그리고 모임-관심사 같은 테이블은 네이밍이 좀 애매해서  우리끼리 알아보기 쉽게 정하는게 나을 것 같습니다!
NoArgsConstructor 어노테이션은 JPA 적용할거 생각해서 미리 붙여놨습니다

Chatting - 채팅
ChattingParticipation - 채팅 참여
ChattingRoom - 채팅방
FavoriteChatting - 채팅 찜
Group - 모임
GroupInterest - 모임-관심사
GroupInterestAnchor 모임-관심사
GroupMembers - 모임 참여
GroupRule - 모임 규칙
Interest - 관심사
InterestCategory - 관심사 카테고리
InterestingNation - 관심국가-사용자
Nation - 관심국가
Post - 게시글
PostImage - 게시글사진
Report - 신고
Rule - 규칙
Schedule - 일정
User - 사용자
UserInterst - 관심사-사용자

2023-07-14 06:32 UTC, jaewonLeeKOR commented
모임 태그 엔티티 추가해주세요!!

2023-07-14 07:04 UTC, minjgziii reviewed
모임-일정 연관관계 매핑 안되어 있는 것 같아용

2023-07-14 11:38 UTC, jaewonLeeKOR requested changes

2023-07-14 11:38 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/GroupMembers.java
erdCloud의 모임참여 테이블을 구현한건가요??
GroupMembers보다 UserGroup이 더 적합한 이름이라고 생각해요🤗

2023-07-14 11:38 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/InterestingNation.java
InterestedCountry가 맞는 표현 같은데 어떻게 생각하시나요?🧐

2023-07-14 11:38 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Nation.java
Nation보다 Country가 더 나은 표현이라 생각하는데 어떻게 생각하시나요?🤓

2023-07-14 11:38 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Schedule.java
> +    private int numberOfPeople;
participantCount가 더 알아보기 쉬운 명명법이라고 생각합니다~!🤨

2023-07-14 11:38 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Tag.java
> +    private String tagContent;
그냥 content라고만 해도 되지 않을까요?🫨

2023-07-14 11:38 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/User.java
> +    private int monthlyMeetNumber;
따로 저장하지 않고 모임, 일정 테이블과 join을 통해 찾을 수 있는 값 같은데 빼도 되지 않을까요?🙃

2023-07-14 11:58 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/domain/User.java
> +    private int entrance; // -> int? String? LocalDate?
저두 글케 생각함당

2023-07-14 12:00 UTC, lxxyxin approved these changes
엔티티별 필드 이름 명명법을 통일하는게 좋을거같아용 그거 말고는 위에서 꽤 이미 수정된거같슴당 고생햇서유👍

2023-07-14 13:34 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/ChattingParticipation.java
넵 pr메세지에 매핑시켜놨습니다!

2023-07-14 13:35 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/Group.java
> +    private String filePath;
imageFilePath로 수정했슴니다

2023-07-14 13:55 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/User.java
> +    private int monthlyMeetNumber;
음 살짝 tradeoff 요소일듯 합니다 monthlyMeetNumber 변수 하나만 있으면 join을 안해도 알 수 있긴한데 어떤게 좋을지 생각해볼만 할 것 같아요

2023-07-14 13:59 UTC, kuk6933 commented
그룹-관심사 처럼 중간 관계 테이블 네이밍은 모두 두 테이블 이름 이어쓰는 방식으로 수정했습니다
ex) UserChatting

2023-07-14 14:05 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/User.java
> +    private int monthlyMeetNumber;
음 매달 초기화하는것도 좀 낭비겠네요 빼는게 나을것같네용

2023-07-15 02:10 UTC, minjgziii approved these changes
고생하셨습니다!!

2023-07-15 07:24 UTC, jaewonLeeKOR approved these changes

2023-07-15 07:26 UTC, merged