Feature/#29/group join
UMC-TEAM-RF/RF-Server pull request #43
Opened 2023-08-01 18:03 UTC by kuk6933

party 가입 신청,  가입(수락시), 거절입니다. 
// 민지 코드랑 합치면서 맞춰보고 merge 예정입니다!

2023-08-03 11:32 UTC, minjgziii requested changes

2023-08-03 11:32 UTC, minjgziii commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    }
모임 참여를 신청하려는 경우, 해당 사용자가 이미 파티에 가입했는지 여부를 확인하는 로직을 추가하는 게 좋을 것 같아요!
joinApply 메소드에 해당 파티의 참여자 목록을 조회해서 사용자가 이미 해당 파티에 참여하고 있는지 확인하고, 이미 가입한 경우 예외를 날리는 게 어떨까요?!

2023-08-03 11:36 UTC, minjgziii commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    public PostApproveJoinRes join(PostApproveJoinReq postApproveJoinReq) throws BaseException {
controller에 있는 네임이랑 같게 approveJoin 어때욥

2023-08-03 16:12 UTC, lxxyxin requested changes

2023-08-05 08:07 UTC, jaewonLeeKOR requested changes

2023-08-05 08:07 UTC, jaewonLeeKOR commented on src/main/resources/application.yml
얘는 커밋을 왜 한거죵?

2023-08-05 08:07 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    public PostApproveJoinRes join(PostApproveJoinReq postApproveJoinReq) throws BaseException {
저도 approveJoin이 나은거 같아욥

2023-08-05 08:07 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +
전반적으로 Validation 부분의 수정이 많이 필요할거 같네요 🤔

2023-08-05 08:07 UTC, jaewonLeeKOR commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
로컬에서 h2 데이터베이스를 돌리기 위해 넣은건가요?
서버에 올릴때는 사용하지 않았으면 좋겠어요 ㅠ

2023-08-05 08:14 UTC, kuk6933 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
엇 항상 주의했었는데 실수했네요 ㅠ 주의하겠습니다

2023-08-05 08:16 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +
전면 수정 들어가겠슴니다!

2023-08-05 08:16 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    }
그렇네용 검증 로직 추가하겠습니다

2023-08-05 08:53 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    public PostApproveJoinRes join(PostApproveJoinReq postApproveJoinReq) throws BaseException {
완료-

2023-08-05 09:00 UTC, kuk6933 commented on src/main/resources/application.yml
얘는 수정사항이 없는데 어째서 올라간건지 모르겠네용

2023-08-06 09:34 UTC, kuk6933 commented
1. main을 pull하고 충돌을 해결해 코드를 main과 동기화했습니다
2. party에서 tag를 사용하지 않아 관련 코드를 삭제했습니다
3. Party를 받아올 때 User의 프로필사진, 닉네임, 국적만을 받아올 수 있도록 했습니다 
4. 코드의 중복을 피하기 위해 리팩토링을 진행했습니다

2023-08-06 11:53 UTC, kuk6933 commented
1. Party를 생성했을때 owner가 자동으로 Party에 들어가도록 수정했습니다

2023-08-07 04:46 UTC, jaewonLeeKOR commented
validation 잘 되어있는지 확인 완료 했나요?

2023-08-07 04:48 UTC, kuk6933 commented
아직 native Count수 확인하는 로직을 추가 안해서 미완성입니다ㅠ  추가하고 review 요청드리겠습니다

2023-08-09 03:20 UTC, kuk6933 commented
validation 추가해봤습니다!!! 혹시 빠진 상황이 있다면 코멘트 부탁드립니다

2023-08-09 12:07 UTC, minjgziii commented on src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
> +    EXCEEDED_PARTY_USER_COUNT(false, 2008, "모임이 가득 찼습니다"),
해당 모임에 가입할 수 있는 인원이 초과되었습니다.
로 바꾸면 어떨까용
EXCEEDED_PARTY_COUNT 오류와 말이 비슷해서 헷갈릴 수도 있을 것 같아요옹~

2023-08-09 14:03 UTC, lxxyxin requested changes

2023-08-10 05:54 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/Party.java
>      private int nativeCount;
Long parse할 일이 있나용?  count같은 경우는 Long쓸 만큼 큰 숫자가 할당될 경우가 없어서 int로 했었습니다!

2023-08-10 06:09 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
> +    EXCEEDED_PARTY_USER_COUNT(false, 2008, "모임이 가득 찼습니다"),
좋네요! 수정하겠습니다~

2023-08-10 06:11 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +            Party party = partyRepository.save(Party.builder()
넵!

2023-08-10 06:48 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +            Party party = partyRepository.save(Party.builder()
JPA는 Dirty Checking기능이 있어서 반영은 될겁니다! 
하지만 쿼리 관점에서는 한번 테스트해볼 필요가 있겠네요!

2023-08-10 08:14 UTC, minjgziii approved these changes
제 눈엔 더이상 문제가 안 보여요... 구미베어 고생하셨습니다~!

2023-08-10 10:02 UTC, jaewonLeeKOR requested changes
최적화를 합시다!! 🧸

2023-08-10 10:02 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        userParty.setUser(user);
계속해서 setParty, setUser를 함께 사용하는 것 같은데 하나의 메서드로 전환할 수 있나요?
따로 메소드를 생성한 이유가 있나요?

2023-08-10 10:03 UTC, jaewonLeeKOR commented
빌드가 제대로 되지 않았네요 확인 해주세요!!

2023-08-10 12:14 UTC, lxxyxin requested changes

2023-08-10 12:44 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    }
넵 해결했습니다 트랜잭션 문제였더라구용

2023-08-10 13:12 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/User.java
> +        this.imageFilePath = "default";
요거는 기본이미지 url나오면 나중에 바꿔줄거라 default로 뒀습니다!

2023-08-10 14:03 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        User user = userService.findUserById(ownerId);
넵~

2023-08-10 14:03 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/User.java
> +        if (userParties.size() > 5) {
RfRule이라는 새로운 클래스를 만들어서 대체했습니다

2023-08-10 14:05 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +    public List<GetUserProfileRes> getUserProfiles(List<UserParty> userParties) {
프론트쪽에서 모임 조회할때 유저 닉네임, 사진, 국적만 따로 달라고해서 만들었습니다

2023-08-11 01:58 UTC, kuk6933 commented
올게 와버렸네요 민지꺼가 푸시됐군요.. 충동해결하겠습니다

2023-08-11 02:00 UTC, jaewonLeeKOR commented
> 올게 와버렸네요 민지꺼가 푸시됐군요.. 충돌해결하겠습니다

혹시 잘 몰라서 그러는데,, 어떤 충동이 생겼는지 알 수 있을까요..?
머지하고 싶은 충동인가요..

2023-08-11 04:30 UTC, jaewonLeeKOR requested changes

2023-08-11 04:30 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/constant/RfRule.java
> +    public static final int maxPartyNumber = 5;
class 형식 이 나을까요?
enum 클래스가 낫지 않을까 생각 됩니다.

2023-08-11 05:13 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
최적화 완료-

2023-08-11 05:44 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
이미 UserParty가 가지고 있는 친구들이라  쿼리를 사용하지 않습니다!

2023-08-11 05:44 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        userParty.setUser(user);
생성자에 넣어봤는데 어떨까요?

2023-08-11 05:50 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/constant/RfRule.java
> +    public static final int maxPartyNumber = 5;
상수 변수 관리는 요런식으로도 많이 하고 저도 선호하는 방식이여서 요렇게 작성해봤습니다

2023-08-11 05:52 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +        }
--완료--

2023-08-11 11:28 UTC, kuk6933 commented
일단 merge하고 conflict는 해결했습니다-- approve 부탁드립니다

2023-08-11 11:30 UTC, lxxyxin approved these changes
구미베어 고생하셨습니다~~

2023-08-12 10:11 UTC, jaewonLeeKOR approved these changes
잘 했을거라 믿어요~!~!~!~!~!~

2023-08-13 05:28 UTC, merged