엔티티 정리 및 Enum 클래스 전환
UMC-TEAM-RF/RF-Server pull request #49
Opened 2023-08-05 06:24 UTC by jaewonLeeKOR

Country -> 국가
Interest -> 관심사
Language -> 언어
Mbti -> mbti
PreferAges -> 선호 연령대
Rule -> 규칙
University -> 대학교
와 같이 enum 클래스를 구성헀습니다.
또한 Request를 Enum의 이름으로 받고, Response를 한글 이름으로 반환하도록 했습니다.
예외적으로 국가는 국가 번호로 Request를 받아 한글 이름으로 Response 하도록 했습니다.

2023-08-05 08:09 UTC, kuk6933 requested changes

2023-08-05 08:09 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/User.java
> +    private List<Language> interestingLanguages;
@ElementCollection이 테이블로 만들어서 관리하는 방식인가용? 
주석 지워도 괜찮을거같아요!

2023-08-05 08:09 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/dto/GetPartyRes.java
>      private LocalDateTime createdDate;
language -> languageName처럼 Name을 붙인 이유를 여쭤봐도 될까요!

2023-08-05 08:12 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/constant/Country.java
> +    ;
이넘 클래스 관리하는게 저게 더 낫더라구요
새로 생성하거나 삭제할때 보통 줄 단위로 해서 세미콜론이 계속 없어졌다 생겼다 해서요 ㅠ
뒤로 옮기는게 나을까요?

2023-08-05 08:14 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/dto/GetPartyRes.java
>      private LocalDateTime createdDate;
한국어 이름으로 내보내는걸 강조하려고 Name을 붙였어요
내보내는 방식은 더 고민해봐야할거 같아요
브랜치 체크아웃 해서 한번 어떤게 나을 지 확인 해봐 주세요~~

2023-08-05 09:18 UTC, lxxyxin approved these changes
바꿀거 되게 많았을텐데 작업하시느라 고생하셨습니다~~ 👍👍

2023-08-05 09:18 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/constant/Mbti.java
> +    private final String name;
String으로 선언된 변수들이 나중에 큰따옴표 안에 있는 이름을 반환할때 쓰이는건가용?

2023-08-05 09:33 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/constant/Mbti.java
> +    private final String name;
이건 빼도 될거 같네용

2023-08-05 09:39 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/dto/GetPartyRes.java
>      private LocalDateTime createdDate;
생각해보니 한국 이름으로 내보낼 필요가 없네요
다시 다 바꿔야겠어요!

2023-08-05 13:18 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/constant/Country.java
> +    ;
아하 개인 성향 차이가 될 수 있겠네용 
다른 분들 의견도 들어보면 좋을것 같아요!

2023-08-05 13:30 UTC, minjgziii commented on src/main/java/org/rf/rfserver/constant/Country.java
> +    ;
저는 평소에 ,CHINA(86L, "china", "중국"); 이렇게 쓰긴 하는데 둘 다 상관 없어여

2023-08-06 02:36 UTC, kuk6933 approved these changes
고생하셨슴니당

2023-08-06 06:24 UTC, minjgziii approved these changes
고생하셨습니당>0< 서버팀장 이재원 짱!!

2023-08-06 06:26 UTC, merged