Feature/#8/schedule crud
UMC-TEAM-RF/RF-Server pull request #55
Opened 2023-08-07 08:12 UTC by lxxyxin

모임 일정 관련 API를 생성하였습니다.

주요 기능
- 일정 생성
- 모임별 일정 조회
- 유저별 일정 조회
- 일정 수정
- 일정 삭제

2023-08-07 10:25 UTC, jaewonLeeKOR requested changes

2023-08-07 10:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/dto/PostScheduleReq.java
> +    private Long id;
이 id는 언제 쓰는건가요?

2023-08-07 10:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +                  .orElseThrow(() -> new BaseException(REQUEST_ERROR));
모임 존재하지 않을경우 REQUEST_ERROR의 결과가 제대로 반환 되던가요??

2023-08-07 10:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +    }
모임의 일정을 조회하는 상황이 어떤 상황인가요?
리스트 형태로 스크롤해서 확인하는 상황이라면 페이징 처리를 해야하고, 
달력 형태로 확인하는 상황이라면 월별로 잘라서 조회가 가능하도록 해야 할 것 같아요!!

2023-08-07 10:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +        }
사용자의 일정을 조회하는 상황이 어떤 상황인가요?
리스트 형태로 스크롤해서 확인하는 상황이라면 페이징 처리를 해야하고, 
달력 형태로 확인하는 상황이라면 월별로 잘라서 조회가 가능하도록 해야 할 것 같아요!!

2023-08-07 10:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +        }
UserParty 테이블을 조회하고 Schedule 테이블을 조회하는것을 따로 해야할까요?
함꼐하는 방법이 없을까요??
또한 for 문으로 데이터베이스에 접근하는경우 쿼리가 대량으로 발생하여 데이터베이스 접근 방법이라고 생각해요
해당 부분은 고쳐야할것 같아요!!

2023-08-07 10:28 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Schedule.java
>      private int participantCount;
참여자 수는 어떤 경우 사용하는 건가요??

2023-08-07 10:40 UTC, jaewonLeeKOR commented
main 브랜치에서 pull 해서  schedule 엔티티에도 BaseEntity 객체를 extend 하도록 하는건 어떤가요?
일정은 생성, 수정일이 사용할 일이 없을까요?

2023-08-08 05:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Schedule.java
>      private int participantCount;
int를 사용한 이유가 있나요??
다른 숫자를 나타내는 변수들은 Long으로 처리하는데 다르게 하셔서요,,
int로 처리하는 경우 다른 곳에서 사용할 시에 Long 타입으로 parse하여 사용해야 해요~!

2023-08-08 05:25 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Schedule.java
> +    private Integer alert;
여기도 Integer를 사용한 이유가 있나요?
Integer를 사용하는 경우 다른 코드와 함께 사용할 시에 Long 타입으로 Parse해서 사용해야 하는 경우가 있어서요~!

2023-08-08 09:14 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/dto/PostScheduleReq.java
> +    private Long id;
확인해보니 불필요한 부분인것 같아서 삭제하겠습니당

2023-08-08 11:08 UTC, kuk6933 requested changes

2023-08-08 11:08 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/schedule/controller/ScheduleController.java
> +    }
식별자를 요청 데이터와 분리하기 위해 PathVariable과 RequestBody를  나눠 사용하셨군요👍

2023-08-08 11:08 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/schedule/dto/PatchScheduleReq.java
> +}
null을 할당하신 이유를 여쭤봐도 될까용?
초기화가 필요하다면 생성자를 이용하는건 어떨까요?

2023-08-09 11:14 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +    }
모임별 조회는 당장 사용하는 기능은 아닌데 나중에 필요할 수도 있을 것 같아서 구현은 해놨습니다!
지금 당장 사용하는 기능은 아닌데 주석처리할까요?

2023-08-09 11:15 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +        }
월별로 잘라서 확인할 수 있도록 수정해놓겠습니다....!

2023-08-09 11:16 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/domain/Schedule.java
>      private int participantCount;
참여자수는 일정 정보 확인할때 띄워줘야해서 사용했습니다 
피그마 화면에 보면 참여인원도 있더라구요!

2023-08-09 11:21 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/dto/PatchScheduleReq.java
> +}
수정할때 일부 변수는 변경되지 않는 부분도 있을 것 같아 null로 할당해놨는데 이 방법에 혹시 문제가 생길 여지가 있을까요?

2023-08-09 15:33 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +                  .orElseThrow(() -> new BaseException(REQUEST_ERROR));
try 위치 조정해서 결과 제대로 나오도록 변경했습니당

2023-08-10 09:07 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +
반영했습니당

2023-08-10 09:31 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/schedule/dto/PatchScheduleReq.java
> +}
NullPointerException안나게 처리만 잘 해주시면 괜찮을것 같아요!

2023-08-10 13:41 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +        }
수정했습니당

2023-08-10 13:45 UTC, lxxyxin commented
수정한거 다시 리뷰 부탁드려요~~

2023-08-11 04:36 UTC, jaewonLeeKOR requested changes

2023-08-11 04:36 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByParties(@Param("parties") List<Party> parties);
`@Param("parties")` 어노테이션이 없어도 잘 돌아가지 않나요??

2023-08-11 04:36 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +        List<Schedule> schedules = scheduleRepository.findByParties(parties);
쿼리가 줄어들던가요?

2023-08-11 06:19 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
> +        List<Schedule> schedules = scheduleRepository.findByParties(parties);
반복문으로 짰던 쿼리보다는 줄어듭니다! 추후에 조금 더 효율적인 방법을 고민해 보겠습니다

2023-08-11 06:43 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByParties(@Param("parties") List<Party> parties);
어노테이션 없으면 에러나서 안돌아갑니당...ㅎㅁㅎ....

2023-08-11 06:44 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByParties(@Param("parties") List<Party> parties);
리스트라 그런건가유

2023-08-11 07:11 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByParties(@Param("parties") List<Party> parties);
아뇽 쿼리문 사용해서 그런거같습니당

2023-08-13 05:11 UTC, kuk6933 approved these changes
conflict만 해결하시면 될 듯 합니다!

2023-08-15 09:09 UTC, lxxyxin commented
수정하면서 아래의 기능을 추가하였습니다.
- 유저별 일정 조회 - 월별 조회 기능 추가
- 모임장 확인 로직 추가

2023-08-16 09:56 UTC, minjgziii reviewed
conflict만 해결하면 될 것 같아용!

2023-08-17 07:25 UTC, merged