Hotfix/#67/get party
UMC-TEAM-RF/RF-Server pull request #68
Opened 2023-08-11 06:32 UTC by minjgziii

2023-08-11 06:37 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/party/dto/GetPartyUserRes.java
> +}
엇...제 ..pr에...있는데

2023-08-12 08:54 UTC, jaewonLeeKOR requested changes
잘 했어요~! 😜

2023-08-12 08:54 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
> +    private String profileImage;
이미지를 처음 저장하거나 수정할 때는 @lxxyxin 께서 사용한 이미지로 받아 S3에 업로드를 한 후 해당 url을 User 테이블에 저장하는게 맞지 않을까요??
어떻게 생각하나요

2023-08-12 08:54 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/party/service/PartyService.java
> +                            .build();
이렇게 길어지는 빌더 타입의 경우는 생성자에 Party 객체를 집어넣는 형태로 바꿔서 사용하는 건 어떤가요?
다들 어떻게 생각하시나요
@minjgziii @kuk6933 @lxxyxin

2023-08-14 13:10 UTC, closed without merging