채팅 신고 API
UMC-TEAM-RF/RF-Server pull request #69
Opened 2023-08-11 12:35 UTC by jaewonLeeKOR

## Description

* [ ] 채팅 신고
* [ ] 신고 타입 Enum 클래스로 관리 하도록 변경

2023-08-13 04:35 UTC, jaewonLeeKOR commented
채팅과 관련 0.01% 정도 밖에 없으니 리뷰 해주세요오,, 제발
@kuk6933 @lxxyxin  @minjgziii

2023-08-13 04:48 UTC, minjgziii commented on src/main/java/org/rf/rfserver/constant/ReportType.java
> +    ,PARTY("그룹")
그룹 -> 모임 바꾸는 거 어떤가욥

2023-08-13 04:49 UTC, minjgziii approved these changes
역시 잘하셨군용 고생하셨습니다!

2023-08-13 04:58 UTC, kuk6933 requested changes

2023-08-13 04:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/report/dto/GetReportRes.java
> +    }
if 세번 보다 else if를 사용하는 것은 어떨까용?

2023-08-13 04:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/report/dto/GetReportRes.java
> +        this.createdAt = report.getCreatedAt();
this는 생략되어도 되지 않을까용? 🤗

2023-08-13 04:58 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/report/dto/PostReportRes.java
> +    }
여기두요!

2023-08-13 05:48 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/report/dto/GetReportRes.java
> +    }
else if보다 if가 더 가독성을 높인다고 생각 해서 if만 사용했어요

2023-08-13 06:03 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/constant/ReportType.java
> +    ,PARTY("그룹")
네 바꾸겠습니다~!

2023-08-14 14:05 UTC, lxxyxin approved these changes
고생하셨습니당~

2023-08-14 14:05 UTC, lxxyxin commented on src/main/java/org/rf/rfserver/domain/Report.java
actor에서 reported로 바꾼게 더 직관적이고 좋은거같아요~~

2023-08-15 04:21 UTC, kuk6933 approved these changes
고생하셨습니다~

2023-08-15 06:14 UTC, merged