Mail 아이디 찾기 / 비밀번호 재설정
UMC-TEAM-RF/RF-Server pull request #70
Opened 2023-08-12 05:00 UTC by minjgziii

## 아이디 찾기
> - 유저가 이메일 입력
> - 해당 이메일을 가진 유저를 찾음 (없으면 해당 사용자 없음 예외 날림)
> - 찾은 유저의 아이디를 메일로 전송

![image](https://github.com/UMC-TEAM-RF/RF-Server/assets/104371003/315be2d5-2512-429c-947a-d3e07a8f9836)

## 비밀번호 재설정
> - 유저가 이메일 입력
> - 해당 이메일을 가진 유저를 찾음 (없으면 해당 사용자 없음 예외 날림)
> - 찾은 유저의 임시 비밀번호를 랜덤 생성 후 해당 유저의 비밀번호를 업데이트
>-  임시 비밀 번호 메일로 전송 (임시 비밀번호는 숫자, 영대문자, 영소문자 6자리 조합)

![image](https://github.com/UMC-TEAM-RF/RF-Server/assets/104371003/876643f6-0133-4fa7-bbbb-4984083d3c5b)

2023-08-12 08:29 UTC, jaewonLeeKOR requested changes
메일 전문가 킴민지! 킴민지! 킴민지!

2023-08-12 08:29 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/user/service/UserService.java
> +    }
비밀번호 재설정을 바로 하는건 좋지 않는 방식이라고 생각 해요..!
혹시나 계정 주인이 아닌 다른 사용자가 이메일만으로 재설정을 요구할 수도 있으니까요
프론트의 일 일수도 있는데 진짜 이메일의 주인인지 확인부터 하고 비밀번호를 재설정 해주는것이 좋다고 생각해요!!

2023-08-13 05:10 UTC, kuk6933 requested changes

2023-08-13 05:10 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/user/service/UserService.java
> +    }
프론트쪽과 협의가 필요하겠네요!
그리고 
"비밀번호 재설정을 위한 이메일이 발송되었습니다. 이메일을 확인해 주세요." 요런 메세지들은 따로 enum이나 class파일을 만들어서 관리해도 괜찮을 것 같아요!

2023-08-13 05:10 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/Mail.java
> +
CODE_SIZE가 재정의 되어있네용!
그리고 characters도 CODE_SIZE처럼 고정이니까 같은 방식으로 선언해주는건 어떨까요?

2023-08-13 12:48 UTC, minjgziii commented
변경된 로직은 description에 업뎃해 놨습니다.

2023-08-15 08:46 UTC, jaewonLeeKOR approved these changes
따봉 민지야! 👍🏻 참 잘 했어요!!

2023-08-15 08:47 UTC, kuk6933 approved these changes
제 pr도 놀러오세요~

2023-08-15 09:08 UTC, lxxyxin approved these changes
메일장인 킴민쥐 고생하셧습니당~~

2023-08-15 10:43 UTC, merged