채팅 추가 구현
UMC-TEAM-RF/RF-Server pull request #71
Opened 2023-08-12 13:39 UTC by jaewonLeeKOR

채팅 (소켓)
> 텍스트
>이미지
-> 클라이언트 측에서 이미지 업로드를 따로 한 후 반환받은 이미지 url을 이용함
> 일정
> 답장
> 초대
> 나가기
> 강퇴

채팅 관련 API
> 소켓 부재기간의 채팅 조회 API
> 3일 지난 메시지 삭제 서비스 (0,6,12,18시 작동)

메인함수 변경
> 서버 시간대 Asia/Seoul 으로 변경

추가 변경 사항
> 채팅용 토픽 설정
> RedisConnectionFactory -> LettuceConnectionFactory 전환
> 채팅 생성 에러 발생 시 전송 타입 생성
> 설명용 주석 생성

2023-08-16 07:37 UTC, jaewonLeeKOR commented
이 PR은 너무 조용합니다
첫번째 Comment를 남겨보세요!
@UMC-TEAM-RF/server-crew @minjgziii @kuk6933 @lxxyxin

2023-08-17 07:11 UTC, kuk6933 requested changes

2023-08-17 07:11 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/chat/dto/GetChatsReq.java
> +}
NoArgsConstructor 없이도 잘 동작하나용? 
ObjectMapper가 기본생성자를 사용해서 있어야 하는것으로 알고있습니다

2023-08-17 07:11 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/constant/MessageType.java
> +    ,KICK_OUT("강퇴")
LEAVE는 퇴장 어떨까용

2023-08-17 07:44 UTC, lxxyxin approved these changes
킹갓재원 짱~

2023-08-17 07:44 UTC, minjgziii approved these changes
conflict만 해결해 주세요 굳~

2023-08-18 05:11 UTC, merged