Feature/#75/recruiting
UMC-TEAM-RF/RF-Server pull request #77
Opened 2023-08-14 09:26 UTC by kuk6933

1. Party에 Boolean 변수인 isRecruiting 추가
2. GetPartyDto에 isRecruting 추가
3. PartyService에 모집 인원이 가득 찼을시 모집마감으로 변경
4. 모임장이 상태를 바꿀수 있도록 togglePartyRecruitment 함수 추가 
5. 가입 신청넣을시 모집중인 모임인지 검증하는 로직 추가

2023-08-17 07:45 UTC, minjgziii approved these changes
고생하셨습니당 굳맨!!

2023-08-18 08:15 UTC, jaewonLeeKOR requested changes

2023-08-18 08:15 UTC, jaewonLeeKOR commented on src/main/java/org/rf/rfserver/domain/Party.java
> +
toggle enum을 생성하고도 Boolean 을 이용하는 이유가 뭔가요?
Boolean으로 관리할거면 Toggle Enum이 없어도 되지 않을까요

2023-08-18 08:57 UTC, kuk6933 commented on src/main/java/org/rf/rfserver/domain/Party.java
> +
Boolean만 사용했다가 알아보시기 힘들것 같아서 넣었는데 뺴도 괜찮을까요?

2023-08-19 12:06 UTC, lxxyxin requested changes

2023-08-21 07:13 UTC, lxxyxin approved these changes
gooooood

2023-08-21 07:35 UTC, merged